### ISSUE TITLE
Module not found: Error: Can't resolve 'utf-8-validate' /  'bufferutil'

### ISSUE THREAD

**Issue by ozcanxbreeze** [CrossBreezeNL/crossmodel#10]
Module not found: Error: Can't resolve 'utf-8-validate' in 'C:\Werkmappen\repos\crossmodel\node_modules\@eclipse-glsp\server\node_modules\ws\lib'

Can't resolve 'bufferutil' in 'C:\Werkmappen\repos\crossmodel\node_modules\@eclipse-glsp\server\node_modules\ws\lib'

These errors appear when you build crossmodel-lang

**Comment by harmen-xb** [comment]
Just checked, and these warnings still appear after PR #34 .
