### ISSUE TITLE
Browser does not refresh after build

### ISSUE THREAD

**Issue by ozcanxbreeze** [CrossBreezeNL/crossmodel#12]
Now when you run "yarn browser:start" and "yarn watch" simultaneously the server gets rebuilt and the changes you made to the code automatically applied.

Would be nice if this feature was extended, so the browser also get refreshed after each rebuild.

**Comment by martin-fleck-at** [comment]
I'm not aware of any hot loading mechanism for Theia. There was a request some time ago (https://community.theia-ide.org/t/how-to-auto-refresh-the-page-when-code-changed/620) but it seems there was never any real follow-up so it might be possible.

**Comment by harmen-xb** [comment]
Since this is currently not supported by Theia, and doesn't seem to be on the backlog I will close this issue for now. Also this issue is not perse an issue of CrossModel, but more for Theia.
