### ISSUE TITLE
Can't have multiple diagrams open at the same time

### ISSUE THREAD

**Issue by ozcanxbreeze** [CrossBreezeNL/crossmodel#16]
When you open the graphical view of two different models, the application freezes most of the time.

**Comment by willem-xbreeze** [comment]
Lookin into the issue:
When two diagram views are opened within either the same model or two different models, the second one does not show all objects, but when looking in the DOM they appear to be there

**Comment by harmen-xb** [comment]
**Steps to reproduce:**

1. Start CrossModel with yarn start:browser
2. Open the yarn-example workspace
3. Create a new diagram and drag some entities in them.
4. Open a second diagram (the existing one).

At step 4 the diagram seems empty.

Now if you close both diagrams and open one of them you see some zooming happening. So it looks like there is something off with the zoom of the diagrams.
