### ISSUE TITLE
Form-view empty after refreshing the page

### ISSUE THREAD

**Issue by ozcanxbreeze** [CrossBreezeNL/crossmodel#17]
When you open a form-view and refresh the browser, the form-view will be empty.

That is because this line in the form-editor-widget.tsx never finishes.
`await this.formEditorService.open(uri);`

The formEditorService(form-server) or the model server has not been initalized.

**Comment by ozcanxbreeze** [comment]
made a quick fix

`if (this.formEditorService.isInitialized()) {
                await wait(2000);
}`

might be worth taking a look at, to find a better solution

**Comment by willem-xbreeze** [comment]
Probably this event is started too soon and needs to wait for the plugins to have started. Take care not to introduce a loop/deadlock

**Comment by harmen-xb** [comment]
I cannot reproduce this error anymore in the latest main. After refresh the form will render, sometimes with a small delay, but it consistently shows the contents.
