### ISSUE TITLE
Update Theia and GLSP to new version

### ISSUE THREAD

**Issue by ozcanxbreeze** [CrossBreezeNL/crossmodel#19]
There is a new version of theia and glsp? The current application has to be updated to these versions.

**Comment by martin-fleck-at** [comment]
There is going to be a GLSP release within the next two weeks and a Theia release at the end of this month. I'd suggest to wait for that.

**Comment by harmen-xb** [comment]
@martin-fleck-at Is the GSLP and Theia release already there?

**Comment by martin-fleck-at** [comment]
Yes, Theia already made their community release (https://github.com/eclipse-theia/theia/releases/tag/v1.40.1) but the GLSP release got delayed for a bit but we are in the finalization phase so it shouldn't be too long now.

**Comment by harmen-xb** [comment]
@martin-fleck-at : Is this the release we were waiting for? https://github.com/eclipse-glsp/glsp/releases/tag/v2.0.0

**Comment by martin-fleck-at** [comment]
@harmen-xb Exactly! Yes, I'd recommend doing one PR to update all the dependencies that build on each other so we do not run into any issues that could be  simply resolved by updating other dependencies. For instance, I would not upgrade Langium as part of this task even though we might also want to think about doing this at some point.

**Comment by harmen-xb** [comment]
Theia and GLSP are updated to their latests version in PR #34 .
