### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'classList')

### ISSUE THREAD

**Issue by ozcanxbreeze** [CrossBreezeNL/crossmodel#20]
![image](https://github.com/CrossBreezeNL/crossmodel/assets/129742920/934880b4-9a00-46e6-a829-39f2a67af121)

**Comment by martin-fleck-at** [comment]
This was fixed in GLSP, see https://github.com/eclipse-glsp/glsp-client/blob/6284e711e2fd9cb9778151ca4eba2a168f6fdb5a/packages/client/src/features/tool-palette/tool-palette.ts#L324

**Comment by harmen-xb** [comment]
@martin-fleck-at I don't see the GLSP-1048 issue listed in any GLSP release yet (https://github.com/eclipse-glsp/glsp-client/releases). Is it already in any release we can use?

**Comment by martin-fleck-at** [comment]
@harmen-xb Yes, we plan a new major release for GLSP very soon (probably by the end of this month) which is why we skipped a release. So we need to wait just a little longer before we can do the upgrade.

**Comment by harmen-xb** [comment]
GLSP was updated to v2.0.0 where this issue was fixed as part of PR #34
