### ISSUE TITLE
can this project achieve similar requirement?

### ISSUE THREAD

**Issue by zrwsmd** [CrossBreezeNL/crossmodel#27]
i want to achieve a requirement(that need to transform industrial Programming Language LD(Ladder Diagram) to other specific lauguage like C++ or PLC ST (Structured Text）language) when graph(Ladder Diagram) changed,corresponding text file(for my requirement is C++ or PLC ST) is changed rather than changing the text file lead to change the graph,can this project achieve similar requirement?

**Comment by harmen-xb** [comment]
@zrwsmd 
Currently this is not natively supported, and it's also not our vision to support this in the future.

With the technology stack used (Langium, GLSP, etc.) it is probably possible to implement this requirement. You can use our codebase as an example to do so.

**Comment by zrwsmd** [comment]
> @zrwsmd Currently this is not natively supported, and it's also not our vision to support this in the future.
> 
> With the technology stack used (Langium, GLSP, etc.) it is probably possible to implement this requirement. You can use our codebase as an example to do so.



> @zrwsmd Currently this is not natively supported, and it's also not our vision to support this in the future.
> 
> With the technology stack used (Langium, GLSP, etc.) it is probably possible to implement this requirement. You can use our codebase as an example to do so.

thanks for your reply

**Comment by harmen-xb** [comment]
@zrwsmd 

We also saw some hurdles and decided to contact @planger from EclipseSource for support. They are a great partner for (support with) implementing this technology.

All the best!

**Comment by zrwsmd** [comment]
> @zrwsmd
> 
> We also saw some hurdles and decided to contact @planger from EclipseSource for support. They are a great partner for (support with) implementing this technology.
> 
> All the best!

thanks a lot,i had contact  and learn a lot from him
