### ISSUE TITLE
No "Open with" in the context menu if file is selected

### ISSUE THREAD

**Issue by ozcanxbreeze** [CrossBreezeNL/crossmodel#7]
When you have a file selected and you want to open it in a different viewing method the open with does not show up in the context menu. 

![image](https://user-images.githubusercontent.com/129742920/232075383-b472be29-a434-4a4c-a3a4-7327abaaf888.png)

**Comment by martin-fleck-at** [comment]
I definitely have noticed that in other Theia-based products as well. Usually switching file selection fixes the problem and once it is working it keeps working.

**Comment by ozcanxbreeze** [comment]
Tested it a bit more and it always happens after you open a diagram.cm file with the "CrossModel Diagram"editor and try to open the same file with a different editor. Does not happen for other files or when you open a diagram.cm with a different editor.

**Comment by ozcanxbreeze** [comment]
probably also related to the property view problem where the tool-pallete seems to steal away the focus. see https://github.com/eclipse-glsp/glsp/issues/1048

**Comment by willem-xbreeze** [comment]
Probably fixable by updating to a new GLSP release. In august there is a 2.0 release.

**Comment by harmen-xb** [comment]
This seems to be solved with the Theia/GLSP update of PR #34 .
